import Link from "next/link";
import { Sparkles, Upload } from "lucide-react";
import { BrowseExplorer } from "@/components/BrowseExplorer";

export default function HomePage() {
  return (
    <div className="space-y-8">
      <section className="overflow-hidden rounded-xl2 border border-border bg-surface p-6 sm:p-8">
        <h1 className="max-w-2xl text-2xl font-bold sm:text-3xl">
          Browse the best GIFs & stickers — or{" "}
          <span className="text-brand">create your own with AI</span>.
        </h1>
        <p className="mt-2 max-w-xl text-muted">
          Upload an image or video, add a prompt, and turn it into a shareable
          meme, sticker or GIF. All generated by AI.
        </p>
        <Link
          href="/create"
          className="mt-5 inline-flex items-center gap-2 rounded-full bg-brand px-5 py-2.5 text-sm font-medium text-white transition-opacity hover:opacity-90"
        >
          <Sparkles size={16} /> Create a meme
          <Upload size={16} className="opacity-70" />
        </Link>
      </section>

      <section>
        <BrowseExplorer />
      </section>
    </div>
  );
}
